name: CD | Dev Docker Image

on:
  push:
    branches-ignore:
      - "refs/tags/*"

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Clear Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Download SD 1.5 Pruned Model (7.7 GB)
        uses: wei/wget@v1
        with: 
          args: -O ./v1-5-pruned.safetensors "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.safetensors"

      - name: "Move SD Model to sd-models dir"
        run: | 
          mkdir /sd-models
          mv ${GITHUB_WORKSPACE}/v1-5-pruned.safetensors /sd-models/v1-5-pruned.safetensors    

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: docker-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}:${{ env.DOCKER_TAG }}
